# path or URL to sample sheet (TSV format, columns: sample, condition, ...)
ref:
  # path/to/reference/gDNA.fasta
  sequence:       /varidata/research/projects/bbc/versioned_references/2022-03-08_14.47.50_v9/data/mm10_gencode/sequence/mm10_gencode.fa
  fai:            /varidata/research/projects/bbc/versioned_references/2022-03-08_14.47.50_v9/data/mm10_gencode/sequence/mm10_gencode.fa.fai
  # path/to/bwa/index/directory
  index:          /varidata/research/projects/bbc/versioned_references/2022-03-08_14.47.50_v9/data/mm10_gencode/indexes/bwa/mm10_gencode
  # path/to/gtf/file/with/transcripts.gtf
  annotation:     /varidata/research/projects/bbc/versioned_references/2022-03-08_14.47.50_v9/data/mm10_gencode/annotation/mm10_gencode.gtf
  # ENCODE blacklist
  blacklist:      /varidata/research/projects/bbc/versioned_references/2022-03-08_14.47.50_v9/data/mm10_gencode/blacklist/mm10_encode_v2.bed
  mito_chr: chrM


# comment out what is not needed in 'addtnl_bigwig_norms'. These are additional approaches to normalize the BigWigs. 'ecoli' is for CutnRun or CutnTag protocols.
addtnl_bigwig_norms:
    #- 'csaw_bkgd'
    #- 'csaw_hiAbund'
    #- 'ecoli'

ecoli_chrom: "ec_Chromosome" # used for normalization if requested

atacseq: false
run_ATACseqQC: false # Does not matter unless atacseq==true.
run_hmmratac: false # Does not matter unless atacseq==true. This option provided because HMMRATAC seems to have issues with low-pass/pilot sequencing data.
  #peakset_for_FRiP: 'narrow'

macs2:
  gsize: "mm"

DiffBind:
  summits: 200 # 100 recommended for ATAC by DiffBind author (https://rdrr.io/bioc/DiffBind/man/DiffBind3.html).
  subtract_controls: True

csaw:
  win_width: 150 # for TFs use 10-20bp
homer:
  run: True
  genome: "mm10" # mm10 and hg38 should be preconfigured; can also be a genome fasta file, but Homer will write to the parent directory of the file, so don't use a versioned_references file directly...symlink to a custom directory should be ok. 
  size: 200

gtf_for_tss_heatmap: /varidata/research/projects/bbc/versioned_references/2022-03-08_14.47.50_v9/data/mm10_gencode/annotation/mm10_gencode.basic.gtf

shared_snakemake_repo: "/varidata/research/projects/bbc/research/shared_snakemake/"

atacseqc:
    known_genes_pkg: TxDb.Mmusculus.UCSC.mm10.knownGene

modules:
  bamtools: bbc2/bamtools/bamtools-2.5.2 
  bedops: bbc2/bedops/bedops-2.4.41
  bedtools: bbc2/bedtools/bedtools-2.30.0
  bwa: bbc2/bwa/bwa-0.7.17
  deeptools: bbc2/deeptools/deeptools-3.5.2
  fastqc: bbc2/fastqc/fastqc-0.12.1
  fastq_screen: bbc2/fastq_screen/fastq_screen-0.14.0
  HMMRATAC: bbc2/HMMRATAC/HMMRATAC-1.2.10 
  macs2: bbc2/macs2/macs2-2.2.7.1
  multiqc: bbc2/multiqc/multiqc-1.14
  picard: bbc2/picard/picard-2.27.5
  preseq: bbc2/preseq/preseq-3.2.0 
  qualimap: bbc2/qualimap/qualimap_v.2.2.2
  R: bbc2/R/alt/R-4.2.1-setR_LIBS_USER
  samblaster: bbc2/samblaster/samblaster-0.1.26
  samtools: bbc2/samtools/samtools-1.17
  trim_galore: bbc2/trim_galore/trim_galore-0.6.10
  ucsc: bbc2/kent-core/kent-core-v448 
  WiggleTools: bbc2/WiggleTools/WiggleTools-1.2.11 
