# path or URL to sample sheet (TSV format, columns: sample, condition, ...)
ref:
  # path/to/reference/gDNA.fasta
  sequence:       /varidata/research/projects/bbc/versioned_references/2021-05-10_16.02.19_v2/data/mm10_gencode_plus_viruses_and_cfmedips/sequence/mm10_gencode_plus_viruses_and_cfmedips.fa
  fai:            /varidata/research/projects/bbc/versioned_references/2021-05-10_16.02.19_v2/data/mm10_gencode_plus_viruses_and_cfmedips/sequence/mm10_gencode_plus_viruses_and_cfmedips.fa.fai
  # path/to/bwa/index/directory
  index:          /varidata/research/projects/bbc/versioned_references/2021-05-10_16.02.19_v2/data/mm10_gencode_plus_viruses_and_cfmedips/indexes/bwa/mm10_gencode_plus_viruses_and_cfmedips
  # path/to/gtf/file/with/transcripts.gtf
  annotation:     /varidata/research/projects/bbc/versioned_references/2021-05-10_16.02.19_v2/data/mm10_gencode_plus_viruses_and_cfmedips/annotation/mm10_gencode_plus_viruses_and_cfmedips.gtf
  # ENCODE blacklist
  blacklist:      /varidata/research/projects/bbc/versioned_references/2021-05-10_16.02.19_v2/data/mm10_gencode/blacklist/mm10_encode_v2.bed
  # space-delimited chroms to keep.
  # REMEMBER TO CHECK THAT THESE ARE ACCURATE FOR THE TARGET SPECIES
  #keep_chroms:    chr1 chr2 chr3 chr4 chr5 chr6 chr7 chr8 chr9 chr10 chr11 chr12 chr13 chr14 chr15 chr16 chr17 chr18 chr19 chrX chrY
  mito_chr: chrM
  # When we filter alignments for peak calling, we remove contigs smaller than 'cutoff'. This is meant to be a way to retain only the nuclear chromosomes (not mitochondrial). Make sure that this value is not larger than any of the chromosomal contigs in your genome.
  chrom_min_bp: 5000000

atacseq: true
run_hmmratac: true # Does not matter unless atacseq==true. This option provided because HMMRATAC seems to have issues with low-pass/pilot sequencing data.
  #peakset_for_FRiP: 'narrow'

macs2:
  gsize: "mm"

gtf_for_tss_heatmap: /varidata/research/projects/bbc/versioned_references/2021-05-10_16.02.19_v2/data/mm10_gencode/annotation/mm10_gencode.basic.gtf

shared_snakemake_repo: "/secondary/projects/bbc/research/shared_snakemake/"
