# path or URL to sample sheet (TSV format, columns: sample, condition, ...)
ref:
  # path/to/reference/gDNA.fasta
  sequence:       /varidata/research/projects/bbc/versioned_references/2022-03-08_14.47.50_v9/data/hg38_gencode/sequence/hg38_gencode.fa
  fai:            /varidata/research/projects/bbc/versioned_references/2022-03-08_14.47.50_v9/data/hg38_gencode/sequence/hg38_gencode.fa.fai
  # path/to/bwa/index/directory
  index:          /varidata/research/projects/bbc/versioned_references/2022-03-08_14.47.50_v9/data/hg38_gencode/indexes/bwa/hg38_gencode
  # path/to/gtf/file/with/transcripts.gtf
  annotation:     /varidata/research/projects/bbc/versioned_references/2022-03-08_14.47.50_v9/data/hg38_gencode/annotation/hg38_gencode.gtf
  # ENCODE blacklist
  blacklist:      /varidata/research/projects/bbc/versioned_references/2022-03-08_14.47.50_v9/data/hg38_gencode/blacklist/hg38_encode_v3.bed
  # space-delimited chroms to keep.
  # REMEMBER TO CHECK THAT THESE ARE ACCURATE FOR THE TARGET SPECIES
  #keep_chroms:    chr1 chr2 chr3 chr4 chr5 chr6 chr7 chr8 chr9 chr10 chr11 chr12 chr13 chr14 chr15 chr16 chr17 chr18 chr19 chrX chrY
  mito_chr: chrM
  # When we filter alignments for peak calling, we remove contigs smaller than 'cutoff'. This is meant to be a way to retain only the nuclear chromosomes (not mitochondrial). Make sure that this value is not larger than any of the chromosomal contigs in your genome.
  #chrom_min_bp: 5000000


# comment out what is not needed in 'addtnl_bigwig_norms'. These are additional approaches to normalize the BigWigs. 'ecoli' is for CutnRun or CutnTag protocols.
addtnl_bigwig_norms:
    #- 'csaw_bkgd'
      #- 'csaw_hiAbund'
      #- 'ecoli'

ecoli_chrom: "ec_Chromosome" # used for normalization if requested

atacseq: false
run_hmmratac: false # Does not matter unless atacseq==true. This option provided because HMMRATAC seems to have issues with low-pass/pilot sequencing data.
  #peakset_for_FRiP: 'narrow'

macs2:
  gsize: "hs"

homer:
  run: True
  genome: "hg38" # mm10 and hg38 should be preconfigured; can also be a genome fasta file, but Homer will write to the parent directory of the file, so don't use a versioned_references file directly...symlink to a custom directory should be ok. 
  size: 200

gtf_for_tss_heatmap: /varidata/research/projects/bbc/versioned_references/2022-03-08_14.47.50_v9/data/hg38_gencode/annotation/hg38_gencode.basic.gtf

shared_snakemake_repo: "/secondary/projects/bbc/research/shared_snakemake/"

atacseqc:
    known_genes_pkg: TxDb.Hsapiens.UCSC.hg38.knownGene

modules:
  bamtools: bbc/bamtools/bamtools-2.5.1
  bedops: bbc/bedops/bedops-2.4.37
  bedtools: bbc/bedtools/bedtools-2.29.2
  bwa: bbc/bwa/bwa-0.7.17
  deeptools: bbc/deeptools/deeptools-3.4.3
  fastqc: bbc/fastqc/fastqc-0.11.9
  fastq_screen: bbc/fastq_screen/fastq_screen-0.14.0
  HMMRATAC: bbc/HMMRATAC/HMMRATAC-1.2.10
  macs2: bbc/macs2/macs2-2.2.7.1
  multiqc: bbc/multiqc/multiqc-1.9
  preseq: bbc/preseq/preseq-2.0.3
  qualimap: bbc/qualimap/qualimap_v.2.2.2
  R: bbc/R/R-4.1.0-setR_LIBS_USER
  samblaster: bbc/samblaster/samblaster-0.1.24
  samtools: bbc/samtools/samtools-1.9
  trim_galore: bbc/trim_galore/trim_galore-0.6.0
  ucsc: bbc/ucsc/ucsc-2020.06.11
